[2025-03-04 15:03:51,343] - ERROR: Error processing request: 'dict' object has no attribute 'loc'
